### ISSUE TITLE
COPS search function with non-english character

### ISSUE THREAD

**Issue by yche2990** [seblucas/cops#425] opened 2019-03-31 13:29 UTC
Thank you for your amazing app.

I really like the APP and I use the Marvin for reading. It does not support search function by typing chinese characters.

I can generate the search results if using english characters. If I type chinese, it gives the found numbers of entries, however, I cannot choose the entry.

Please help to fix.

**Comment by glls** [comment] 2019-04-08 15:02
Hi, it worked for me with the embedded server, 
I imported a Chinese book to calibre, 
calibre changed the filename from all.pdf to Yi Yu - Bei Jing Zhong Guo Yu Yan Wen Hua Xue Xiao.pdf
and COPS can download the book from this link : 
http://localhost:8080/library/Bei%20Jing%20Zhong%20Guo%20Yu%20Yan%20Wen%20Hua%20Xue%20Xiao/Yi%20Yu%20%2821%29/Yi%20Yu%20-%20Bei%20Jing%20Zhong%20Guo%20Yu%20Yan%20Wen%20Hua%20Xue%20Xiao.pdf

**Comment by yche2990** [comment] 2019-04-08 15:09
I am not saying that the downloading function is not working. The only issue I have is the search function. If I use the marvin 3 to search by chinese characters, it will not generate any results. If I search in the internet explorer (English language version), the typing will generate search result with "?" not the chinese characters.

**Comment by seblucas** [comment] 2019-06-16 19:24
@yche2990 
First sorry for the delay, real life took its toll lately :(
I'll try to reproduce your problem with a free epub (I'll try this one : https://www.gutenberg.org/ebooks/24264)

**Comment by seblucas** [comment] 2019-06-19 20:07
@yche2990 / @glls  I either cannot reproduce the problem or don't understand it : 

![image](https://user-images.githubusercontent.com/437682/59796670-4f291c00-92de-11e9-9fb6-ef29853ba0fa.png)

Please explain the problem more clearly.

**Comment by seblucas** [comment] 2019-06-22 17:18
Closing for now, please open another issue if you can help to understand this problem.

**Closed by seblucas** 2019-06-22 17:18 UTC
