### ISSUE TITLE
Update COPS on Synology

### ISSUE THREAD

**Issue by kotliary** [seblucas/cops#277] opened 2016-07-01 18:20 UTC
I saw that the COPS has been updated here to version 1.0.0. 
Should we wait for an updated package on synocommunity or can it be updated manually? Would you please provide some instruction how to do such update without loosing current configuration and database?
Thanks a lot.

**Comment by seblucas** [comment] 2016-07-01 22:30
1.0.0 is not yet out (matter of days). But I won't try to make it work with DSM, I know it don't for now and I have no idea why.

**Comment by kotliary** [comment] 2016-07-02 15:15
Thanks for the reply. Sorry that I was wrong about the update. Just looked in CHANGELOG file.

**Comment by vinpel** [comment] 2016-07-04 15:29
i've downloaded the "master.zip" today and install without problem : 
DS212 with DSM 6.0.1-7393 Update 1

- created a /volume1/virtualhosts/calibre/cops
- unziped all in cops
- placed all my calibre directory in /volume1/virtualhosts/calibre/calibre
- copied config_local.php.exemple to config_local.php
```
<?php
    if (!isset($config))
        $config = array();

    /*
     * The directory containing calibre's metadata.db file, with sub-directories
     * containing all the formats.
     * BEWARE : it has to end with a /
     */
    $config['calibre_directory'] = '../calibre/';

    /*
     * Catalog's title
     */
    $config['cops_title_default'] = "COPS";

    /*
     * use URL rewriting for downloading of ebook in HTML catalog
     * See README for more information
     *  1 : enable
     *  0 : disable
     */
    $config['cops_use_url_rewriting'] = "1";
```

 - Personnalised PPH open_basedir : **/volume1/virtualhosts:XXXXXXXX**
 - added a virtualhost (i own a domain name) : 
 -  * by name : cops.mydomaine.com
 -  * webroot : /volume1/virtualhosts/calibre/cops
 -  * Apache HTTP 5.6
in a ssh session: 
 - cd /volume1/virtualhosts/calibre
 - sudo chown -R http:http *
and i enter my user passord (not root/admin) but i've added it to sudo

All seem to work fine, what is the problem ?

**Comment by seblucas** [comment] 2016-07-04 16:36
I'll admit I didn't test for long but a simple reinstall of the package didn't work. More information seems to be available here : https://github.com/seblucas/cops/issues/261

**Comment by mbirth** [comment] 2016-07-05 10:47
No need for a package. Just checkout COPS to a folder in your Web Station, make the Calibre-data folder writable for everyone, same for the thumbnails folder, modify `open_basedir` in Web Station, make sure all needed PHP plugins are enabled and you should be good to go. Tested it on my DS415+ with DSM6.

**Comment by seblucas** [comment] 2016-07-05 13:37
The package made it easier for average Joe users but as it's confirmed by at least 2 users, I'll close this.

@vinpel 
thanks for the detailed report
@mbirth 
Thanks for the confirmation and the easier method

**Closed by seblucas** 2016-07-05 13:37 UTC
